//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Thea2Translator.Logic.Languages;

namespace Thea2Translator.DesktopApp.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default { get { return defaultInstance; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string WorkingDirectory { get { return ((string)(this["WorkingDirectory"])); } set { this["WorkingDirectory"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UserName { get { return ((string)(this["UserName"])); } set { this["UserName"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string UserId { get { return ((string)(this["UserId"]))?.ToUpper(); } set { this["UserId"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Polish")]
        public Languages Language { get { return ((Languages)(this["Language"])); } set { this["Language"] = value; } }

        #region Mod
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModTitle { get { return ((string)(this["ModTitle"])); } set { this["ModTitle"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModBody { get { return ((string)(this["ModBody"])); } set { this["ModBody"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModTitle_Translation_Debug { get { return ((string)(this["ModTitle_Translation_Debug"])); } set { this["ModTitle_Translation_Debug"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModBody_Translation_Debug { get { return ((string)(this["ModBody_Translation_Debug"])); } set { this["ModBody_Translation_Debug"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModTitle_Names { get { return ((string)(this["ModTitle_Names"])); } set { this["ModTitle_Names"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModBody_Names { get { return ((string)(this["ModBody_Names"])); } set { this["ModBody_Names"] = value; } }
        #endregion

        #region DataBase
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastItemDatabase { get { return ((string)(this["LastItemDatabase"])); } set { this["LastItemDatabase"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BookmarksDatabase { get { return ((string)(this["BookmarksDatabase"])); } set { this["BookmarksDatabase"] = value; } }
        #endregion
        #region Modules
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastItemModules { get { return ((string)(this["LastItemModules"])); } set { this["LastItemModules"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BookmarksModules { get { return ((string)(this["BookmarksModules"])); } set { this["BookmarksModules"] = value; } }
        #endregion
        #region Names
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string LastItemNames { get { return ((string)(this["LastItemNames"])); } set { this["LastItemNames"] = value; } }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string BookmarksNames { get { return ((string)(this["BookmarksNames"])); } set { this["BookmarksNames"] = value; } }
        #endregion
    }
}
